export const GET_ALL_TRIPS = 'GET_ALL_TRIPS';
export const GET_ALL_TRIPS_SUCCEEDED = 'GET_ALL_TRIPS_SUCCEEDED';
export const GET_ALL_TRIPS_FAILED = 'GET_ALL_TRIPS_FAILED';

export const ADD_NEW_TRIP = 'ADD_NEW_TRIP';
export const ADD_NEW_TRIP_SUCCEEDED = 'ADD_NEW_TRIP_SUCCEEDED';
export const ADD_NEW_TRIP_FAILED = 'ADD_NEW_TRIP_FAILED';